# Generated by Django 4.2.1 on 2023-08-28 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 19, 32, 1, 858761)),
        ),
    ]
