# Generated by Django 5.2.5 on 2025-08-20 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 14, 41, 49, 106619)),
        ),
    ]
