# Generated by Django 5.2.5 on 2025-08-20 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 14, 58, 15, 694891)),
        ),
    ]
